# Site settings
baseurl:             "http://miguelcatalan.github.io"
url:
header-img:          img/main.jpg

# Metadata
tagline:             hi there!
title:               Miguel Catalan
email: miguel.catalan.banuls@gmail.com
copyright_name: Miguel Catalan
description: "Write your site description here. It will be used as your sites meta description as well!"

# Social
twitter_username: mcatalanb
github_username:  MiguelCatalan
facebook_username:  miguel.catalan
email_username:  miguel.catalan.banuls@gmail.com
stackoverflow_link: http://stackoverflow.com/users/1994530/miguelcatalan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 2
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
